# Generated by Django 2.2.10 on 2020-06-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200604_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/menu/photo'),
        ),
    ]
